### PR TITLE
Changed to serverspec v2 compatibility also added WinRm support

### PR DESCRIPTION
**Pull request by vvchik**
I have changed backend support  of this plugin for serverspec v2 because serverspec v1 is almost obsolete/
Also winrm is often used for windows testing it different from PR#11 because that PR uses serverspec v1 as backend

### CODE REVIEW

**Comment by StefanScherer** [comment]
@vvchik this is a great improvement. I've tested your PR and this fully replaces my PR #11 ;-)
I have played with your two examples for an Ubuntu and Windows box. Both your `spec_helper.rb` files are empty, so for beginners they just can create their test files. Nothing else to explain.

IMHO a combination with PR #10 could make a new version of vagrant-serverspec.

**Comment by vvchik** [comment]
@StefanScherer Thank you, It was main idea, simplicity for beginners, and flexibility with spec_helper.rb for advanced users. Also code is refactored in serverspec v2 style.

In fact I already merge PR #10 with my code in branch [ErrorhandlingByAthak](https://github.com/vvchik/vagrant-serverspec/tree/ErrorhandlingByAthak) but didnt include it to this PR because it is not my code.

And you right, it is good practice to follow [SemVer](http://semver.org/) ruleset. If @jvoorhis will accept this PR it will be good idea to change major number, because of backwards incompatible changes for previously written tests that need to be rewritten.

**Comment by jvoorhis** [comment]
@vvchik, all, thanks for your contributions, and for using
vagrant-serverspec! I'll do my best to review and put together a release.

On Sun, Jan 4, 2015 at 5:54 AM, Volodymyr Babchynskyy <
notifications@github.com> wrote:

> @StefanScherer <https://github.com/StefanScherer> Thank you, It was main
> idea, simplicity for beginners, and flexibility with spec_helper.rb for
> advanced users. Also code is refactored in serverspec v2 style.
>
> In fact I already merge PR #10
> <https://github.com/jvoorhis/vagrant-serverspec/pull/10> with my code in
> branch ErrorhandlingByAthak
> <https://github.com/vvchik/vagrant-serverspec/tree/ErrorhandlingByAthak>
> but didnt include it to this PR because it is not my code.
>
> And you right, it is good practice to follow SemVer <http://semver.org/>
> ruleset. If @jvoorhis <https://github.com/jvoorhis> will accept this PR
> it will be good idea to change major number, because of backwards
> incompatible changes for previously written tests that need to be rewritten.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jvoorhis/vagrant-serverspec/pull/12#issuecomment-68633625>
> .
>



-- 
Jeremy Voorhis

**Comment by vvchik** [comment]
Good news, @jvoorhis, thank you very much.
I also merged error handling changes by athak to this PR for easier merging. So PR #10 included in this one.

**Comment by vvchik** [comment]
hi @jvoorhis 
Kindly remember about this request.
May be you need some help?

**Comment by jvoorhis** [comment]
Hi @vvchik. Sorry for the delay. Since my time is somewhat limited for the near-term, I would be happy to add you as a collaborator if you like.

**Comment by vvchik** [comment]
Hi @jvoorhis It is, OK, anyway you merged it and it is great!
Thank you for proposition, to be collaborator, it is an honor for me, I agree.

**Comment by tehmaspc** [comment]
rock! nice work!

**Pull request merged**
