### PR TITLE
Add examples clear and ssh connection close

### LINKED ISSUE #22: Using two serverspec suites on two separate VMs
I have two vm's setup like this:

```
    config.vm.define "ubuntu" do |ubuntu|
      ubuntu.vm.box = "ubuntu/vivid64"
      ubuntu.vm.provision :serverspec do |ubuntu_spec|
        ubuntu_spec.pattern = ['**/acceptance/ubuntu/**/*_spec.rb', '**/acceptance/all/**/*_spec.rb']
      end

    end

    config.vm.define "centos" do |centos|
      centos.vm.box = "opscode-centos-6.7"

      centos.vm.provision :serverspec do |centos_spec|
        centos_spec.pattern = ['**/acceptance/centos/**/*_spec.rb', '**/acceptance/all/**/*_spec.rb']
      end
    end
```

centos suite is run for CentOS VM and ubuntu suite for the Ubuntu VM. The"all" suite should be run for both VMs. Everything works fine when running 

```
vagrant provision centos --provision-with serverspec
```

or

```
vagrant provision ubuntu --provision-with serverspec
```

but when running 

```
vagrant provision --provision-with serverspec
```

it tries to run both centos and ubuntu suites in both VMs and some of the test cases of course fails.

### PR DESCRIPTION
**Pull request by achaussier**
This resolve #22 :
- Always clear examples between runs
- Close existing SSH connection between runs

### CODE REVIEW

**Comment by vainikkaj** [comment]
Good stuff, unfortunately this does not work for me when winrm is used as communicator.
Full error available in https://gist.github.com/vainikkaj/021ecf1a216d5448f782

Vagrant 1.8.1
Host: Windows 7
Guest: Windows 2012r2

**Comment by vainikkaj** [comment]
Everything works again after shared examples are loaded using `load` instead of `require`

**Comment by achaussier** [comment]
Hello,
Thanks, good to know. I'll add a commit to update readme file today and add a note about that point.

**Comment by vvchik** [comment]
Looks good, please update Readme and I will merge it.

**Comment by achaussier** [comment]
Readme updated.

**Comment by achaussier** [comment]
Hello, @vvchik, can you have some time to merge it if all is always ok ?

Thanks

**Comment by vvchik** [comment]
Done, sorry I missed your update in readme

**Comment by achaussier** [comment]
No problem, thanks :+1: 

Have a nice day

**Pull request merged**
